// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7i6WhTF1CkZX-fyIGqkqeVbgIDxQoLG4',
    appId: '1:395905526132:web:7a0c00ae0b58472df0a421',
    messagingSenderId: '395905526132',
    projectId: 'code-dev-reach',
    authDomain: 'code-dev-reach.firebaseapp.com',
    storageBucket: 'code-dev-reach.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw7W3mIAt0AG4gerbT9PPG4Ezh-EHAXYY',
    appId: '1:395905526132:android:018f9c51398e6113f0a421',
    messagingSenderId: '395905526132',
    projectId: 'code-dev-reach',
    storageBucket: 'code-dev-reach.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6MVINMezzt7Mj2rdcwMefOFwkxIULBGA',
    appId: '1:395905526132:ios:971094cfdcf5c5c9f0a421',
    messagingSenderId: '395905526132',
    projectId: 'code-dev-reach',
    storageBucket: 'code-dev-reach.appspot.com',
    iosBundleId: 'com.example.codeDevReach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6MVINMezzt7Mj2rdcwMefOFwkxIULBGA',
    appId: '1:395905526132:ios:e7d613f6abd68607f0a421',
    messagingSenderId: '395905526132',
    projectId: 'code-dev-reach',
    storageBucket: 'code-dev-reach.appspot.com',
    iosBundleId: 'com.example.codeDevReach.RunnerTests',
  );
}
